### ISSUE TITLE
sample apears broken (but isn't)

### ISSUE THREAD

**Issue by chriscamacho** [supernovaengine/supernova-samples#1]
https://github.com/supernovaengine/supernova-samples/blob/master/skeletal_animation/main.cpp

could do with some text, "press space to animate"

**Comment by eduardodoria** [comment]
This samples is still incomplete. I'm trying to finish new version of Supernova Engine entity-component-system based to after that finish all samples.

**Comment by eduardodoria** [comment]
Samples are with self-explanatory texts now.
